apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: myreplicaset
  labels:
    tier: myfrontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-nginx
  template:
    metadata:
      name: myapp
      labels:
        app: myapp-nginx
    spec:
      containers:
        - name: myapp
          image: nginx
